import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 min-h-screen flex flex-col">
        <div className="container mx-auto p-4 flex-1 flex flex-col">
          {/* 헤더 */}
          <header className="bg-blue-600 text-white p-4 rounded-lg shadow-md mb-4">
            <h1 className="text-xl font-bold text-center">My Web App</h1>
          </header>

          {/* 메인 콘텐츠 */}
          <main className="flex-1 bg-white p-4 rounded-lg shadow-md mb-4">
            {children}  {/* 각 페이지의 내용이 이곳에 들어옵니다 */}
          </main>

          {/* 하단 네비게이션 */}
          <Navigation />
        </div>
      </body>
    </html>
  );
}
